### ISSUE TITLE
Paper?

### ISSUE THREAD

**Issue by kirklandWater1** [bfsujason/bertalign#1]
Hi, is there a published paper where I can learn more about this alignment tool?

Thanks!

**Comment by bfsujason** [comment]
Yes. Please check [this article on DSH] (http://track.smtpsendmail.com/9032119/c?p=tJbgf8u37g3SPM9j2KhCAFzSHB8zKF_3lrAaMSB9PbNJ-01lGyRDUm1d3IhpeUAFAGWWJQfPZz_nvWjWi6NuCuwib1U92dwYnEExojY1PnoP9U723136q978Mh-iMdxmk1WqIPPBczM1_J4CCZFn2NAVVBMSI7VdmAof5_yOLIJglltmlr68pO5HHLugH825oHbslag5EZW1UrwqLYDHOe0hCatTkC2Xy0jcr6iDh-c5CZNBtfSwBqjOT4_pSTnbGkEjbX0gnMUYcmLwyWFJ48v29daP6aaqmlWidsaUpX4=) for more details about Bertalign.
